### ISSUE TITLE
DS214+

### ISSUE THREAD

**Issue by lkraider** [jinlife/Synology_Photos_Face_Patch#21]
Can I use this plugin on DS214+ ? What other models does it work on?

**Comment by lkraider** [comment]
DS214+ CPU MARVELL Armada XP MV78230

**Comment by jinlife** [comment]
I have no idea about this model, and you should not able to use the so file directly since it is not for Marvell CPU. It is only for X86_64 CPU.  
Also it looks like 214+ is not supported at all according to https://kb.synology.com/en-ro/DSM/tutorial/Which_Synology_NAS_models_support_the_facial_recognition_feature_on_Synology_Photos

You could patch it by youself with [Win64 PatchElfSharp](https://github.com/jinlife/Synology_Photos_Face_Patch/tree/main/bin/PatchELFSharp-Win64)
[Refer ](https://github.com/jinlife/Synology_Photos_Face_Patch/tree/main/bin)

**Comment by lkraider** [comment]
Thanks for the pointers! I will close the issue for now.
